apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orysx-dicom-viewer-ingress
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    kubernetes.io/ingress.class: 'nginx'
spec:
  tls:
    - hosts:
        - test.api.orysx.com
      secretName: orysx-tls
  rules:
    - host: orysx.com
    - host: orysx.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: orysx-dicom-viewer-service
                port:
                  number: 80
    - host: api.orysx.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: orysx-api-service
                port:
                  number: 80
