apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orysx-api-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  
spec:
  rules:
  - host: test.api.orysx.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orysx-api-service
            port:
              number: 80
 