import { AccountTypes, FeatureSlugs, TimeUnits } from "../../../common/interfaces";

export const planSeedData = [
  {
    name: 'Regular',
    price: 0,
    currency: 'USD',
    ranking: 1,
    validity: 9999,
    isDefault: true,
    recurring: false,
    features: {
      [AccountTypes.PATIENT]: {
        [FeatureSlugs.SESSION]: 5,
        [FeatureSlugs.SESSION_FILES]: 100,
        [FeatureSlugs.SPECIALIST_INVITES]: 5,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 1,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 30,
        [FeatureSlugs.CHAT]: 10,
        [FeatureSlugs.VIDEO]: 45,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: 5,
        [FeatureSlugs.AI_DIAGNOSTICS]: 5,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.SPECIALIST]: {
        [FeatureSlugs.SESSION]: 5,
        [FeatureSlugs.SESSION_FILES]: 5,
        [FeatureSlugs.SPECIALIST_INVITES]: 1,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 1,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 30,
        [FeatureSlugs.CHAT]: 10,
        [FeatureSlugs.VIDEO]: 45,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: 5,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.BUSINESS]: {
        [FeatureSlugs.SESSION]: 3,
        [FeatureSlugs.SESSION_FILES]: 3,
        [FeatureSlugs.SPECIALIST_INVITES]: 3,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 0,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 10,
        [FeatureSlugs.CHAT]: 5,
        [FeatureSlugs.VIDEO]: 45,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: 5,
        [FeatureSlugs.AI_DIAGNOSTICS]: 3,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
    },
  },
  {
    name: 'Silver',
    price: 10000,
    currency: 'USD',
    ranking: 2,
    recurring: true,
    validity: 1,
    timeUnit: TimeUnits.MONTH,
    trialPeriod: 1,
    trialTimeUnit: TimeUnits.MONTH,
    features: {
      [AccountTypes.PATIENT]: {
        [FeatureSlugs.SESSION]: -1,
        [FeatureSlugs.SESSION_FILES]: -1,
        [FeatureSlugs.SPECIALIST_INVITES]: 10,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 5,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 365,
        [FeatureSlugs.CHAT]: 30,
        [FeatureSlugs.VIDEO]: 120,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: -1,
        [FeatureSlugs.AI_DIAGNOSTICS]: -1,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.SPECIALIST]: {
        [FeatureSlugs.SESSION]: 25,
        [FeatureSlugs.SESSION_FILES]: 5,
        [FeatureSlugs.SPECIALIST_INVITES]: -1,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 10,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 365,
        [FeatureSlugs.CHAT]: 30,
        [FeatureSlugs.VIDEO]: 120,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: 25,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.BUSINESS]: {
        [FeatureSlugs.SESSION]: 25,
        [FeatureSlugs.SESSION_FILES]: 5,
        [FeatureSlugs.SPECIALIST_INVITES]: 30,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 0,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 365,
        [FeatureSlugs.CHAT]: 30,
        [FeatureSlugs.VIDEO]: 120,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: 25,
        [FeatureSlugs.ANALYTICS]: 'access',
      },
    },
  },
  {
    name: 'Gold',
    price: 10000,
    currency: 'USD',
    ranking: 2,
    recurring: true,
    validity: 1,
    timeUnit: TimeUnits.MONTH,
    trialPeriod: 1,
    trialTimeUnit: TimeUnits.MONTH,
    features: {
      [AccountTypes.PATIENT]: {
        [FeatureSlugs.SESSION]: -1,
        [FeatureSlugs.SESSION_FILES]: -1,
        [FeatureSlugs.SPECIALIST_INVITES]: -1,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 10,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: -1,
        [FeatureSlugs.CHAT]: -1,
        [FeatureSlugs.VIDEO]: -1,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: -1,
        [FeatureSlugs.AI_DIAGNOSTICS]: -1,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.SPECIALIST]: {
        [FeatureSlugs.SESSION]: 5,
        [FeatureSlugs.SESSION_FILES]: 5,
        [FeatureSlugs.SPECIALIST_INVITES]: 1,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 1,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: 30,
        [FeatureSlugs.CHAT]: 10,
        [FeatureSlugs.VIDEO]: 45,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: 5,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.BUSINESS]: {
        [FeatureSlugs.SESSION]: -1,
        [FeatureSlugs.SESSION_FILES]: -1,
        [FeatureSlugs.SPECIALIST_INVITES]: -1,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: -1,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 0,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: -1,
        [FeatureSlugs.CHAT]: -1,
        [FeatureSlugs.VIDEO]: -1,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: -1,
        [FeatureSlugs.ANALYTICS]: 'access',
      },
    },
  },
  {
    name: 'Platinum',
    price: 10000,
    currency: 'USD',
    ranking: 2,
    recurring: true,
    validity: 1,
    timeUnit: TimeUnits.MONTH,
    trialPeriod: 1,
    trialTimeUnit: TimeUnits.MONTH,
    features: {
      [AccountTypes.PATIENT]: {
        [FeatureSlugs.SESSION]: undefined,
        [FeatureSlugs.SESSION_FILES]: undefined,
        [FeatureSlugs.SPECIALIST_INVITES]: undefined,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: undefined,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: undefined,
        [FeatureSlugs.CHAT]: undefined,
        [FeatureSlugs.VIDEO]: undefined,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: undefined,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.SPECIALIST]: {
        [FeatureSlugs.SESSION]: -1,
        [FeatureSlugs.SESSION_FILES]: -1,
        [FeatureSlugs.SPECIALIST_INVITES]: -1,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: -1,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: -1,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: -1,
        [FeatureSlugs.CHAT]: -1,
        [FeatureSlugs.VIDEO]: -1,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: undefined,
        [FeatureSlugs.AI_DIAGNOSTICS]: -1,
        [FeatureSlugs.ANALYTICS]: undefined,
      },
      [AccountTypes.BUSINESS]: {
        [FeatureSlugs.SESSION]: 100,
        [FeatureSlugs.SESSION_FILES]: 10,
        [FeatureSlugs.SPECIALIST_INVITES]: 75,
        [FeatureSlugs.ALLOTED_FILE_STORAGE]: undefined,
        [FeatureSlugs.NON_SPECIALIST_INVITES]: 0,
        [FeatureSlugs.SESSION_RETENTION_PERIOD]: -1,
        [FeatureSlugs.CHAT]: 100,
        [FeatureSlugs.VIDEO]: -1,
        [FeatureSlugs.OTHER_PEER_REVIEW]: undefined,
        [FeatureSlugs.VIEW_PEER_REVIEWS]: 5,
        [FeatureSlugs.AI_DIAGNOSTICS]: -1,
        [FeatureSlugs.ANALYTICS]: 'access',
      },
    },
  },
].map((plan, id) => ({ id: id + 1, ...plan }));