export const specializationSeedData = [
  { title: 'Allergist' },
  { title: 'Anesthesiologist' },
  { title: 'Cardiac Surgeon' },
  { title: 'Cardiologist' },
  { title: 'Colon and Rectal Surgeon' },
  { title: 'Critical Care Medicine Specialist' },
  { title: 'Dermatologist' },
  { title: 'Emergency Care Surgeon' },
  { title: 'Emergency Medicine Specialist' },
  { title: 'Endocrinologist' },
  { title: 'Family Physician' },
  { title: 'Gastroenterologist' },
  { title: 'General Surgeon' },
  { title: 'Geriatric Medicine Specialist' },
  { title: 'Hematologist' },
  { title: 'Hospice and Palliative Medicine Specialist' },
  { title: 'Immunologist' },
  { title: 'Infectious Disease Specialist' },
  { title: 'Internist' },
  { title: 'Medical Geneticist' },
  { title: 'Nephrologist' },
  { title: 'Neurologist' },
  { title: 'Neurosurgeon' },
  { title: 'Obstetricians and Gynecologist' },
  { title: 'Oncologist' },
  { title: 'Ophthalmologist' },
  { title: 'Orthopedic Surgeon' },
  { title: 'Osteopath' },
  { title: 'Otolaryngologist' },
  { title: 'Paediatric Surgeon' },
  { title: 'Pathologist' },
  { title: 'Pediatrician' },
  { title: 'Physiatrist' },
  { title: 'Plastic Surgeon' },
  { title: 'Podiatrist' },
  { title: 'Preventive Medicine Specialist' },
  { title: 'Psychiatrist' },
  { title: 'Pulmonologist' },
  { title: 'Radiologist' },
  { title: 'Rheumatologist' },
  { title: 'Sleep Medicine Specialist' },
  { title: 'Sports Medicine Specialist' },
  { title: 'Surgical Oncologist' },
  { title: 'Thoracic Surgeon' },
  { title: 'Urologist' },
  { title: 'Vascular Surgeon' },
];
