apiVersion: v1
kind: Service
metadata:
  name: orysx-redis-service
  namespace: test
  labels:
    app: orysx-redis-service
spec:
  selector:
    app: orysx-redis
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 6379   # It is listening on port 80 so I changed it  