apiVersion: v1
kind: Service
metadata:
  name: orysx-api-service
  namespace: test
  labels:
    app: orysx-api-service
spec:
  selector:
    app: orysx-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      #targetPort: 9000 # The app itself is not listening on 9000
      targetPort: 3001   # It is listening on port 80 so I changed it  