apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orysx-ingress
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    kubernetes.io/ingress.class: 'nginx'

    kubernetes.io/ingress.allow-http: "true" # I added this
    kubernetes.io/ingress.class: nginx # I added this
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/tls-acme: "true"

spec:
  tls:
    - hosts:
        - orysx.com
      secretName: orysx-tls
    - hosts:
        - api.orysx.com
      secretName: orysx-tls-api
    - hosts:
        - dicom.orysx.com
      secretName: orysx-tls-dicom
  rules:
    - host: orysx.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: orysx-webapp-service
                port:
                  number: 80
    - host: api.orysx.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: orysx-api-service
                port:
                  number: 80
    - host: dicom.orysx.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                # name: orysx-api-service
                name: orysx-dicom-viewer-service
                port:
                  number: 80